config/routes.rb
Rails.application.routes.draw do
  resources :publications
  root 'sections#index', as: "home"
  resources :sections
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/publicacion.rb
class Publicacion < ApplicationRecord
end

app/models/publication.rb
class Publication < ApplicationRecord
end

app/models/seccion.rb
class Seccion < ApplicationRecord
end

app/models/section.rb
class Section < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
      render html: "<h1>Hola, bienvenido a BD-Chan!</h1>".html_safe
    end
  end

app/controllers/post_controller.rb
class PostController < ApplicationController
    def index
        @books = ["Post: Ayuda amiwos", "Ayudenme me aburro en cuarentena recomienden juegazos", "18 de Marzo"]
      end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
end

app/controllers/seccions_controller.rb
class SeccionController < ApplicationController
    def index
        @seccions = Seccion.all
      end
    def new
        @seccions = Seccion.new
    end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
    def index
        @sections = Section.all
    end
    def new
        @sections = Section.new
        
    end
    def create
        @sections = Section.new(section_params)
        if @sections.save
          redirect_to @sections
        else
          render :new
        end
    end
    def show
        @sections = Section.find(params[:id])
        #redirect_to home_path, notice: "Se ha creado la seccion exitosamente"
    end
      
      private
        def section_params
          params.require(:section).permit(:name)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/helpers/seccion_helper.rb
module SeccionHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: name %>
  <% end -%>
  
    <title>Anotherworld</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/post/index.html.erb
<h1>Libros</h1>
<a href="<%= home_path %>">Ir al Home</a>

<table border="1">
  <thead>
    <tr>
      <th>Nombre</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/seccion/cualquiercosa.html.erb
<h1>Libros</h1>
<table border="1">
  <thead>
    <tr>
      <th>Título</th>
      <th>Descripción</th>
      <th>Fecha de Publicación</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.description %></td>
        <td><%= book.publication_date %></td>
        <td>
          <%= link_to "Mostrar", book %>
          <%= link_to "Editar", edit_book_path(book) %>
          <%= link_to "Eliminar", book, method: :delete, data: { confirm: "¿Estás seguro de eliminar este libro?" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/seccion/index.html.erb
<h1>Bienvenido a BD-CHAN</h1>
<a href="<%= home_path %>">Ir al Home</a>

<table border="1">
  <thead>
    <tr>
      <th>Secciones</th>
      <th>Fecha Creacion</th>
    </tr>
  </thead>
  <tbody>
    <% @seccions.each do |sec| %>
      <tr>
        <td><%= sec.nombre %></td>
        <td><%= sec.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/seccion/new.html.erb
<h1>Crea tu nueva seccion</h1>
<%= form_for @seccion do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/seccion/seccion.html.erb
<h1>Bienvenido a BD-CHAN</h1>
<a href="<%= home_path %>">Ir al Home</a>

<table border="1">
  <thead>
    <tr>
      <th>Secciones</th>
    </tr>
  </thead>
  <tbody>
    <% @secciones.each do |seccion| %>
      <tr>
        <td><%= sccion %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/sections/index.html.erb
<h1>Bienvenido a BD-CHAN</h1>

<%= link_to "Crea una nueva seccion", new_section_path %>

<table border="1">
  <thead>
    <tr>
      <th>Secciones</th>
      <th>Fecha Creacion</th>
    </tr>
  </thead>
  <tbody>
    <% @sections.each do |sec| %>
      <tr>
        <td><%= link_to sec.name, sec %></td>
        <td><%= sec.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/sections/new.html.erb
<h1>Indica el nombre que tendra la seccion</h1>
<%= form_for @sections do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/sections/show.html.erb
<h1>Publicaciones de @sections.name</h1>
<div>Nombre: <%= @sections.name %></div>